Timer, backend and CloudFunction for Washing Machines
Swent-Fall-2024-team-10/leazy pull request #107
Opened 2024-11-10 18:34 UTC by mdesautel

This PR (built on top of @userdarius frontend for these screens) features the implementation of backend and cloud methods, as well as timer computation and syncing, for the Washing Machines screens. Below is an explanation of their functionality:

The listing screen now includes a picker modal so the tenant can set a cycle duration for the machine he clicks on (credit of picker if needed: https://www.npmjs.com/package/react-native-timer-picker/v/1.4.0?activeTab=readme). 
Once the picker is set, the machine object updates its (new) attributes occupiedBy, startTime and estimatedFinishTime, to calculate the remaining time before the end of the cycle. 
It computes and displays this timer every second, achieved by the Intervals methods that allow to schedule the execution of a callback at fixed intervals in time. 

Timers and intervals consts are cleaned up and updated when needed with helper methods, ensuring each machine is linked with its own and current timer.

https://github.com/user-attachments/assets/a11d0b95-c913-4dcd-b275-bcf621885b02

Note: the reloading part aims to show that timers are persistent across recompositions.

This PR also includes a CloudFunction deployed to Firebase, designed to send a notification to the user that occupies the machine when its cycle is about to end. 
A new folder "functions" was created by Firebase when initiating functions, to manage and deploy cloud functions. 

Instead of being triggered by changes in the washing machines collection (which would launch it way more than it needs to), it reacts to changes in a new collection, "notifications", pushed by the frontend directly when the timer is three minutes from the estimatedFinishTime. 
That way, the cloud function doesn't poll every minute or so (just waiting for the time to send a notification, and potentially missing it if it doesn't check at the correct time). It is more efficient and straighforward to trigger it only once per cycle, because we already perform the same sort of repeated task in the frontend, and the time to send is by nature at a fixed point in the future. 

We still use a cloudFunction to manage the sending of notifications via the backend, to not expose the FCM token of the user (and have security breaches). Once the cloud function is finished, it simply deletes the document in firebase.

![fonctions firebase](https://github.com/user-attachments/assets/7aa2be2e-8f82-45d0-b7f6-71319eaa9786)

![Capture d'écran 2024-11-10 182321](https://github.com/user-attachments/assets/fb7ca1e6-bba7-443f-8c5a-aaa3fbcf67e6)

Note: as Expo Go doesn't support push notification sending, we have to test on an native environment build, and I don't have an android. For the moment, I tested by sending logs to the console just after sending out the notification. Also, I checked Firebase for the creation of this collection and associated documents (see above picture).

The method used by the frontend to create a new document is defined in the firestore.ts file, "createMachineNotification". Also, another model method is used, "getWashingMachinesQuery", needed by the new listener to correctly fetch the list of machines upon modification. This listener is needed on top of the refresh scroll, to avoid concurrencies when two users want to lock the same machine for example, so they can't both have access to the "set timer" button.

2024-11-13 10:44 UTC, userdarius requested changes
Overall great work integrating the backend for the washing machines! I loved the notification feature although it would help to also have it available offline for the user who set the timer. The timer picker is smooth to use and the user experience is clean and intuitive (see comments for small remarks on UX). Also thank you for using the shared components we discussed like SubmitButton. I mentioned a couple small changes and improvements that should be made before merging this to main but otherwise we should be on our way! Thanks a lot Madeline!

2024-11-13 10:44 UTC, userdarius commented on firebase/firestore/firestore.ts
> +export async function getAllLaundryMachines(residenceId: string) {
We should aim to keep consistency in the naming here so using WashingMachines everywhere instead of LaundryMachines.

2024-11-13 10:44 UTC, userdarius commented on firebase/firestore/firestore.ts
> +export async function createMachineNotification(userId: string) {
Same thing goes for here, rename createMachineNotification to createWashingMachineNotification for consistency.

2024-11-13 10:44 UTC, userdarius commented on functions/src/index.ts
Love the notification feature! Great job. I was just wondering if we could maybe also have this feature offline for the user who sets the timer initially so he can get notified even if his device isn't connected to the internet.

2024-11-13 10:44 UTC, userdarius commented on package.json
> +    "react-native-timer-picker": "^1.0.0",
I added this dependency alongside expo-linear-gradient as they were not included in your latest commit. Should work fine now when running npm install.

2024-11-13 10:44 UTC, userdarius commented on app/screens/laundry_machines/WashingMachineScreen.tsx
> +                      "Calculating..."}
I think for UX sake it would be better to just say Starting... this is nitpicking of course but it's just more user friendly I feel.

2024-11-13 10:44 UTC, userdarius commented on app/screens/laundry_machines/WashingMachineScreen.tsx
Something I would like to have as a user when starting a timer is to be able to cancel the timer at anytime from the card. At the moment once the timer starts there is no way to cancel the timer and a small button underneath the in use tag would be helpful.

2024-11-13 10:44 UTC, userdarius commented on app/screens/laundry_machines/WashingMachineScreen.tsx
> +            [laundryMachineId]: "Cycle completed",
There is a small issue here since once the cycle completes the card does not update to allow the user to reset the state to Available. It stays locked in the cycle completed state and does not update. I suggest you add a button underneath to allow the user who started the timer and for who the cycle completed to be able to "empty the washing machine" and set it's state back to available for other users to be able to use. 
![Screenshot 2024-11-13 at 11 36 36](https://github.com/user-attachments/assets/5963c10a-ff66-4f51-8158-48957e4b4190)

2024-11-14 22:06 UTC, userdarius commented on firebase/firestore/firestore.ts
> +export async function getAllLaundryMachines(residenceId: string) {
This is not urgent we can fix this later

2024-11-14 22:06 UTC, mdesautel commented on app/screens/laundry_machines/WashingMachineScreen.tsx
> +                      "Calculating..."}
I am not sure if it should be saying Starting... because the user could think the timer restarts everytime he gets on the screen.

2024-11-14 22:10 UTC, mdesautel commented on firebase/firestore/firestore.ts
> +export async function getAllLaundryMachines(residenceId: string) {
As all the functions in firestore.ts, as well as the collection in the database use the naming LaundryMachine, I don't thnik it would be a good idea to modify everything into WashingMachine. I will rather modify the name of the method "getWashingMachinesQuery" to "getLaundryMachinesQuery" for consistency.

2024-11-14 22:10 UTC, mdesautel commented on firebase/firestore/firestore.ts
> +export async function createMachineNotification(userId: string) {
(see comment above)

2024-11-14 23:22 UTC, mdesautel commented on app/screens/laundry_machines/WashingMachineScreen.tsx
> +            [laundryMachineId]: "Cycle completed",
I just pushed a fix for both of your suggestions regarding the canceling of the timer and the reset of the machine's state upon completion of the user's cycle.

2024-11-14 23:22 UTC, mdesautel commented on app/screens/laundry_machines/WashingMachineScreen.tsx
(see comment below)

2024-11-14 23:27 UTC, userdarius commented on firebase/firestore/firestore.ts
> +export async function getAllLaundryMachines(residenceId: string) {
Agreed

2024-11-14 23:28 UTC, userdarius commented on app/screens/laundry_machines/WashingMachineScreen.tsx
> +                      "Calculating..."}
Oh ok fair point I did not consider that it re renders every time

2024-11-15 00:34 UTC, merged