Chore/refactor code and styling sheets
Swent-Fall-2024-team-10/leazy pull request #108
Opened 2024-11-11 08:24 UTC by AdrienDeschenaux

Hello team!

This PR is about refactoring styling of the app, this was done by, as much as possible, creating new constants in the styles.ts file. 
The main difficulty about this task is that I had to keep the intention of the person who created the screen while using as much as possible shared components and shared styling.

### Modifications that were done : 

- Color restyling : I tried to replace the color hex code in most of the files by constants defined in the styles.ts
- Screen position of items : I tried to replace as much as possible the positions on the screen, padding and margin to percentages instead of pixel values, in order to avoid having problem when the app is running on different screen resolution. This follow the request I made during last Monday meeting about using mostly percentage values (this was also mentioned during Friday 1 November meeting).
- Dimensions : I tried to use shared dimensions for Icons that are used across the app when possible, in the same idea I added a dimension constant for buttons 
- Icons : I changed to use the 'Icon' component to replace the use of character such as `X` `<` and `>` that were used as button's icons

### Side notes :

In order to be able to reuse components as much as possible I had to slightly modify the Submit button so that it can get a image as optional icon so that the google sign up button on the sign up screen is more coherent with other buttons.

I removed a lot of styles that were not used in local styles sheet, this is something we should be careful in the future as it could be easily avoided by reusing existing styles.

The main goal of all these modification is to make our life easier in the future modifications of the styling of the app

2024-11-12 19:35 UTC, baudoin-csp commented on app/components/StatusBadge.tsx
It works great! Thanks for taking the time to find the correct values 👍

2024-11-12 19:41 UTC, baudoin-csp commented on app/components/buttons/CloseConfirmation.tsx
Thanks for all your modifications. I have 2 questions:
- why top field in the overlay went from -200 to 0%?
- As we don't often use rgba values in the project I think it can be more consistant to {background: #000000; opacity: 0.2;} instead of 'rgba(0, 0, 0, 0.25)'. You can look at https://simplecss.eu/rgbatohex.html for more info.

2024-11-12 19:46 UTC, baudoin-csp commented on app/screens/auth/SignInScreen.tsx
That's a good way to leverage the submit button component!

2024-11-12 19:53 UTC, baudoin-csp commented on app/components/buttons/SubmitButton.tsx
Really great, if it's not too big to ask, could you just remove the unnecessary comment? :)

2024-11-12 20:00 UTC, baudoin-csp requested changes
That's a great PR! I think it will useful for us in the future as sometimes I was a bit lost between the different styles used across the screens.

2024-11-13 18:14 UTC, AdrienDeschenaux commented on app/components/buttons/CloseConfirmation.tsx
0% allow us to chose the position in proportion of the screen instead of the number of pixel, this is a better practice so that the component is displayed at the same place for any screen resolution.

I changed the rgba value in my last commit 👍🏻

2024-11-13 20:14 UTC, baudoin-csp commented
Thanks for adding the modifications Adrien! I approve this PR

2024-11-13 20:14 UTC, baudoin-csp approved these changes

2024-11-13 20:15 UTC, merged