UI : Screen for the situation Report form.
Swent-Fall-2024-team-10/leazy pull request #160
Opened 2024-11-21 19:36 UTC by AdrienDeschenaux

Hello team,

Here's my PR for the UI design regarding the screens for the situation report screen

### Pictures of the screen

<p align="center">
  <img src="https://github.com/user-attachments/assets/96e45643-5cde-44d0-a3b3-4b0e4b89b5c8" alt="Image 1" width="30%" />
  <img src="https://github.com/user-attachments/assets/0fc9565b-b53e-4c4e-902e-0ae67c78f8a5" alt="Image 2" width="30%" />
  <img src="https://github.com/user-attachments/assets/f1ac0fcf-7540-4369-8141-1e347f5de8c1" alt="Image 3" width="30%" />
</p>

### Description : 

This PR is only about a UI task, which mean that it is not "working" completely as some features rely on the back-end. I implemented 2 pickers and 2 input fields that are static and always displayed whatever the situation report it is. But for the `Situation report items` I created a component such that it will be able to display automatically a list that represent a situation report layout, that could be defined by a landlord (at least that was what we planed to do during this weeks meeting). 

This code include `const` that represent fake situation report values and fake picker items, as it was built without the back-end, the next step should be to create the back-end that will allow easy communication between this UI and the back-end, that should consist on a stored layout for the situation report, completing and filling a complete form. 

### Design choices :

For the design the only element that has not been created was the picker which came from `react-native-picker-select`.
I used as much shared styles as it I felt was correct, but in the end a lot of components on this screen are really specific to this screen (which is why I created most of them directly in this screen and not in an other file).

The global component I created are : 
- `SeparationLine.tsx` : a straight line that can be used in screen that could be reused in other screens
- `TickingBox.tsx` : as the name mention this is a ticking box that can be reused in other screen in case we need it

I also created a few local component, that I feel are only meaningful for this screen (therefore only locally defined):
- `TenantNameGroup` : A group with a gray background for the name and surname field, used for `Arriving Tenant` and `Leaving Tenant`
- `SituationReportItem` : this is a single item of a situation report, this is the component which will be using the back-end function to fully display a complete situation report layout
- `PickerGroup` : Just like `TenantNameGroup` this is a component that allow us to display the Picker in a group that has the same layout styling as in the figma.

### Testing : 

#### How to test this ? : 
If you're interested in testing this on your simulator, you should know that this is a landlord screen and therefore it requires you to authenticate with a landlord account (or create one if you don't already have one) 

#### Coverage : 
Regarding the testing, I'm not sure that the CI works already completely (because of tests of other screens that were not passing) so I put there screenshot (for what it is worth) to show that my screen and my components are fulfilling the requirement of 80% line coverage (4th column on the screenshot);

![image](https://github.com/user-attachments/assets/d98b5487-f312-473a-b7da-883d049e44cc)
![image](https://github.com/user-attachments/assets/5cd5c690-f57f-4c08-aceb-f0d666d6081c)
![image](https://github.com/user-attachments/assets/efdaa712-3570-4f9a-9c2b-b468b9c7defd)

### Next step : 

The next step should be to think a build a robust back-end that will allow an easy communication between the front-end and the back-end, regarding this I already started thinking about how to store the layout in the database and how to interact with it as it was one of the point we discussed during this weeks meeting. 

### PS : 

I fixed the ReportScreen component for the close confirmation because we could see through the overlay and it looked buggy, this was fixed by using RGBA value in the background color styling of the `CloseConfirmation.tsx` component

2024-11-21 22:56 UTC, mdesautel commented on app/screens/landlord/SituationReportScreen.tsx
> +            <TickingBox checked={checked3} onChange={setChecked3} />
Here, I think you could set the other two boxes to false in the three cases, so that we can't click on both 'original condition' and 'abnormal wear' for example

2024-11-21 23:01 UTC, mdesautel commented on app/__tests__/SituationReportTest.test.tsx
> +
You should do more tests than just rendering each element, for example clicking on the pickers and checking that it can change values, or ticking some boxes for the normal/abnormal wear for different items.
As I mentioned in an other comment, if you implement the setting to false for the two other boxes of the line when clicking on one, you can also test that it disables the buttons.
I know the backend hasn't been implemented yet so you can't test that the changes are saved to the database, but you can already test that it displays the changes on the screen:)

2024-11-21 23:35 UTC, mdesautel requested changes
Hi, thank you for your PR! Overall great work, the form looks user-friendly and modulable. I mentioned a few things in other comments that I think should be improved, but the screen already works fine! (for the frontend at least) I will wait on Rayane's review before merging, and feel free to answer my comments if you don't agree, right now I will mark this review as 'changes requested' mainly for the test cases and the ticking problem, but the other improvements are less urgent:)

2024-11-21 23:35 UTC, mdesautel commented on app/screens/landlord/SituationReportScreen.tsx
> +      <ScrollView style={[appStyles.screenContainer]}
Here you can add a 'overflow = "hidden",' to the style of the container (maybe you have to create one to wrap the scrollview for it to work), in order to not have the content impeding on the header when scrolling down, which is not very aesthetic (see the second picture you uploaded)

2024-11-21 23:35 UTC, mdesautel commented on app/screens/landlord/SituationReportScreen.tsx
> +  // Picker group to select residence and apartment
Maybe you could make the pickers to be the same size as the other fields for arriving and departing tenants? I feel like it would be more harmonious.

2024-11-22 07:49 UTC, AdrienDeschenaux commented on app/screens/landlord/SituationReportScreen.tsx
> +  // Picker group to select residence and apartment
Hey, thank you for your comment,

Actually, changing the dimension of the picker will make the text inside it being cropped and we could not see the whole text for the residence for example, that's why I don't think it would be a ideal to do that.

You may say that I could then increase the length of the input fields, but actually with the text that there is in the box, it would then be displayed over two lines which would be pretty ugly, in my opinion

2024-11-22 07:52 UTC, AdrienDeschenaux commented on app/screens/landlord/SituationReportScreen.tsx
> +      <ScrollView style={[appStyles.screenContainer]}
Hey I added it, but it doesn't change anything on my end (testing on a Samsung galaxy S8 running with android)

2024-11-22 08:10 UTC, AdrienDeschenaux commented on app/__tests__/SituationReportTest.test.tsx
> +
I added the test you required in my latest commit

2024-11-22 13:59 UTC, mdesautel approved these changes
Alright thank you for these changes! All good now

2024-11-23 16:19 UTC, merged