Feature/backend situation report
Swent-Fall-2024-team-10/leazy pull request #183
Opened 2024-11-25 22:38 UTC by AdrienDeschenaux

Hello Team!

Here's my PR implementing back-end functionalities so that the situation report screen can be completed with the planed functionalities.

EDIT : I noticed that there is a lot of lines changed, this is because I first wanted to use the firebase emulator for testing for which I updated the emulator that was already installed in the project (but not used) but I gave up on using it because I don't think it is setup to run on the CI, therefore I used mocking of the firebase functions instead for the testing.

In the following paragraphs I will try to explain as clearly the functions I created and why I created, I'll try to be precise enough but if you don't understand one of my implementation, feel free to leave a comment so that we can have a discussion about it (you can also reach me out on telegram if you prefer) 

## Data-structure organization : 

The way I organized the situation report in the database is based on one idea ; each residence will have a layout for the situation report, this should be shared among all the apartment and therefore this layout is stored in the residence document. The first idea I had for this layout would have been to use list of lists, or list of tuples in order to represent the fact that situation report item could be grouped or not ( for example a bed is composed of a structure, a mattress and personally in my room in the situation report it includes drawers under the bed. But other items, like walls, doors, chairs ... could be single items ).

The solution I came up after some research and discussion with @ShinUrech the format in which the layout is stored in database is a list of `string`. The idea is that each element in this list can be thought of as a "group" of items. Each string is formatted the following way : 

`Item:ITEMNAME0,Status:STATUS0,Item:ITEMNAME1,Status:STATUS1...` 

so that when it is parsed, each string result in his own list and we end up with the list of lists I originally wanted which will allow the front end to make the difference between groups (lists where :  `number of elements / 2 > 1`, because each element has both a `name` and a `status`). This way of the problem of storing the `SituationReportLayout` is reduced to the problem of storing a single `string[]` in the residence document. 

( Note : The format used to store the `SituationReportLayout` will be the same as the format used to store a filled situation report )

concerning the types modification/creation, I modified the following types : 

- `Apartement` : Now apartment contain a reference to a `SituationReport` since each apartment is related to a tenant and a residence there is no need to link the `SituationReport` to anything else.
- `SituationReport` : You may ask : ' Why do you create a type for `SituationReport` but not for `SituationReportLayout`, the answer is that, a `SituationReportLayout` is only a list of strings, whereas the `SituationReport` should contain  : 
  - the date
  - arriving and leaving tenant
  - the apartementID 
  - filled situation report file.
  - the remarks (if any)
- `Residence` : Now residences contains the list of string `string[]` which represents the layout

If I'm not mistaken those are the only changes I made to the `types`

As I mentioned above, when we want to use the layout to fill a situation report, we need to parse the database representation, which result in the front-end representation. 

For example : 

```
     const toConvert = [
            "Item:groupe1,Status:0", "Item:groupe2,Status:0"
        ];

        const expeted = [
            ["groupe1", 0],
            ["groupe2", 0]];

````

Now I will briefly explain what the purpose of each function is 

## `SituationReport.ts` : 

- `parsedGroup` :  parse group in the database
- `toFrontendFormat` : Allow you to get the front-end format of the database situation report list
- `toDatabaseFormat` : Allow you to convert a front-end format into a database format (so that you can store a filled situation report) 
- `addGroupToLayout` : this function was made in prevision of the functionality allowing the tenant to modify the layout of the situation report, this is unlikely to be implemented this week as this would be part of a different screen 
- `removeGroupFromLayout`: Same as for `addGroupToLayout` but this one allow you to remove a group of items from the layout 
- `changeStatus` : Allow you to change the status of an element in the list given, (update the front-end list to the correct state)

## addition to `firestore.ts` : 

- `addSituationReport` : This function create the `situationReport` document in the database and add a reference to the `situationReport` to the given apartment 
- `deleteSituationReport` : This function handle deletion of a `situationReport` (for example when there is a tenant change), handle deletion of the `situationReport` document and remove the reference from the apartment as well
- `addSituationReportLayout` : add a situation report layout in the residence document 
- `getSituationReportLayout` : get the situation report layout from the residence document (useful when we need to create a new situation report that can be filled) 
- `getSituationReport`: : get the situation report (the situation report that was filled and is stored in the apartment) this was implemented in prevision of other screen that might need this (such as the personal information where we might want to give access to the situation report to the tenant)

## Testing : 

This PR obviously contains the unit tests for all the function mentioned, there might be a coverage problem with the function in the firestore file (as all the other functions don't have unit tests merged on main yet, only my code is covered, hopefully it still reach the requirement, it seems to be the case locally at least). 

## Next step : 

The next step will be to integrate those changes to the already implemented front-end and make everything work together with the back-end

Let me know if you'd like more information about my work!

2024-11-27 15:52 UTC, mahdiatallah requested changes
Great PR overall. I just have some remarks that I added for each specific piece of code. I also wanted to ask you about some parts of the your design.

1. Is it okay if groups don't have names? It could be something as simple as adding NAME:GROUPNAME at the beginning of the string in firebase.
2. Consider using a custom type for the state (with some toString() function to put it in the group string). It would make the code clearer.
3. For the front-end you can freely control the type, so consider using something more  object-oriented than just a list of list as it would provide with a clean facade to work with and would be more idiomatic.
4. I know it's a bit late after all the work you did but don't you think storing layouts in a single json parsable string would be better? The current implementation seems a bit ad hoc.

2024-11-27 19:53 UTC, AdrienDeschenaux commented on app/utils/SituationReport.ts
> +                acc += index === group.length - 1 ? `Status:${item}` : `Status:${item},`
It was necessary because I used the , to parse, I think that it was a bit messy so in the refactoring I changed this so that we avoid this kind of hacky solution.

But now, no more ternary conditional operator thanks to the JSON!

2024-11-27 19:54 UTC, AdrienDeschenaux commented on app/utils/SituationReport.ts
> +export function removeGroupFromLayout(layout: (string | number)[][], index: number){
Same as for my previous comment, this was also removed when refactoring with the JSON

2024-11-27 20:01 UTC, AdrienDeschenaux commented on app/utils/SituationReport.ts
> +    if (layout.length <= groupIndex || layout[groupIndex].length <= itemIndex * 2 + 1 || nextStatus === -1){
Yes you're right I changed this code so that it now throw an exception when invalid index are used.

2024-11-27 20:03 UTC, AdrienDeschenaux commented on types/types.ts
> +  reportDate: string;
Hey I agree with you, if I'm not mistaken we're also using a string for the `MaintenanceRequest` 👍🏻

2024-11-27 20:17 UTC, AdrienDeschenaux commented
Hey @mahdiatallah thanks again for your review, I made the changes you requested, I ended up even increasing the coverage 😎 Let me know if those changes are according to what you had in mind !

2024-11-28 00:38 UTC, mahdiatallah approved these changes
Great ! The changes look good to me. Just be sure to pull from main before merging 🚀

2024-11-28 08:24 UTC, merged