Create auth methods and user creation methods
Swent-Fall-2024-team-10/leazy pull request #20
Opened 2024-10-10 09:41 UTC by ShinUrech

Firebase 
- Initialize firebase in the project: root/firebase/firebase.tsx root/.firebasesrc
- Initialize firebase emulators for auth
- Initialize firebase auth and firestore: root/firebase/auth/auth.ts and root/firebase/firestore/firestore.ts
- Install firebaseui

Methods linked to authentication: root/firebase/auth/auth.ts
- login methods with google auth provider and email and password 
- sign in methods with googe and email and password
- account email modification for the account
- password change method
- account sign out method
- account deletion method 
JEST unit-tests for methods above: root/__tests__/auth.tests.ts

2024-10-10 17:00 UTC, AdrienDeschenaux commented on ui-debug.log
> +Node.js v18.5.0
Does this file need to be pushed ? I feel that this file shouldn't be pushed, let me know if it should be merged and if you could explain me why that would be great.

2024-10-11 07:12 UTC, AdrienDeschenaux commented on ui-debug.log
> +Node.js v18.5.0
Thank you for your feedback we'll check this in order to merge your branch soon

2024-10-11 07:21 UTC, userdarius requested changes
Clean PR some review needed by @ShinUrech for the package dependencies

2024-10-11 07:21 UTC, userdarius commented on firestore-debug.log
I don't think we need this if we could add it to the gitignore it would be best.

2024-10-11 07:21 UTC, userdarius commented on package.json
We should not use the react test renderer lib

2024-10-11 07:21 UTC, userdarius commented on __tests__/auth.test.ts
LGTM

2024-10-11 07:21 UTC, userdarius commented on firebase/auth/auth.ts
LGTM

2024-10-11 07:21 UTC, userdarius commented on firebase/firebase.ts
Looks good although (nitpicking) we could simplify the export to keep the code more concise

2024-10-11 07:55 UTC, userdarius approved these changes

2024-10-11 08:36 UTC, merged