Add street no field to the ResidenceCreationScreen
Swent-Fall-2024-team-10/leazy pull request #208
Opened 2024-12-04 17:13 UTC by ShinUrech

# Add Street Number Field to the ResidenceCreationScreen

While working on my weekly task, I noticed the `streetNumber` field in the `Residence` type. Since the **Figma design** for the `ResidenceCreationScreen` did not include the street number of the address, I decided to:

1. Add it to the **Figma mockup**.
2. Implement the corresponding changes in the UI.

### Design Tweak Proposal
![Screenshot from 2024-12-04 18-01-44](https://github.com/user-attachments/assets/8d5a5755-61b5-483e-9784-21e1c3a39272)  
![Screenshot from 2024-12-04 18-02-05](https://github.com/user-attachments/assets/a683788a-439a-4f88-8cab-d1886f8a974e)

### Changes Made
- **Rearranged the layout**:
  - Moved the `City` field below the `Zip Code` field.
  - Used the remaining space in the row to include the `Street Number` field.
- This change ensures:
  - A cleaner, more visually appealing layout.
  - Avoids having three elements in a single row, which was aesthetically unpleasing.

### Implementation
- Updated the Figma design to reflect the proposed changes.
- Implemented the new layout in the UI code, ensuring the `streetNumber` field is correctly handled.

2024-12-05 19:38 UTC, AdrienDeschenaux requested changes
Hey Shin, Thank you for the modifications you did, I feel some styling could be beneficial to this screen and maybe we could do it now, but it could also be integrated in a task about refactoring of the styling.

I put this as a change requested for now but I'm open to discussion in case we move this to an other issue

2024-12-05 19:38 UTC, AdrienDeschenaux commented on app/screens/landlord/ResidenceCreationScreen.tsx
Hey Shin, thank you for your work! 

The changes done to this screen are indeed a good solution, I have just a small request regarding a little bit of... styling! 
I think this screen could really be enhanced with a really quick styling : 
- First I think this screen deserves to have a title, I think that the current styling isn't at the level of the functionalities implemented which is too bad in my opinion
- Then I feel that the input text fields could be wrapped in a view with a little bit of padding (or margins) so that they don't take almost all the width, let me know how you feel about that but I feel that it could be better if the fields are as wide as the buttons to update the .xlsx elements

2024-12-05 23:07 UTC, ShinUrech commented on app/screens/landlord/ResidenceCreationScreen.tsx
As for the Title, this is a slip up from my part. I added it in my latest commit! I also agreed that the screen deserved a bit of horizontal padding, wish granted!

2024-12-06 07:46 UTC, AdrienDeschenaux commented on app/screens/landlord/ResidenceCreationScreen.tsx
Great changes! thank you. I'll accept this PR right now and merge it into main

2024-12-06 07:47 UTC, AdrienDeschenaux approved these changes

2024-12-06 07:47 UTC, merged