Type and firestore methods for the news
Swent-Fall-2024-team-10/leazy pull request #239
Opened 2024-12-07 19:24 UTC by mdesautel

This PR introduces a new type, News, that will be displayed in the feed of the tenant on his dashboard, sent by his landlord.
It features attributes such as timestamps for the creation/update of the news, the ids of the landlord and tenant, a boolean to indicate if it was read as well as the timestamp for the reading time, and most importantly the title and content of the news (that can also contain images).

I also created several ViewModel methods in the firestore.ts file, among which we find the basic ones: creation, deletion, update, getter of a news. In addition to those, we can directly filter and retrieve news directed at a specific user, with the option of specifying that only unread news are requested. In the same vein, the method markNewsAsRead updates only the fields isRead and ReadAt with true and Date.now() respectively. Lastly, the landlord can add one or more images to his news (e.g. to prove once and for all that the 'giant spider infestation' in the basement was probably just a Halloween decoration left behind by the previous tenants).

Let me know if you have questions!

2024-12-09 17:25 UTC, userdarius requested changes
Hi thanks again for this PR @MadelineDesautel. It'll help me a lot for the UI implementation. Some comments I had were regarding types and UX which I mentioned below. I think adding a feature for the Landlord to see who has seen post is a good idea which I did not think of when implementing the figma design we should add it!

2024-12-09 17:25 UTC, userdarius commented on types/types.ts
> +  ReadAt: Timestamp;
Is this parameter really important? I think the isRead is the only one we really need for updating the feed.

2024-12-09 17:25 UTC, userdarius commented on types/types.ts
> +  ReceiverID: string;
Should we add a feature for the manager to see who has seen the post in the manage newsfeed screen for the landlord then?

2024-12-13 12:32 UTC, mdesautel commented on types/types.ts
> +  ReadAt: Timestamp;
Yes indeed if you have more than one user that can read the news, then it would not reflect accurately the reading time. I added this because it is an attribute that I saw in many messaging apps, where it says 'read at xx:xx', but we don't have to implement that. Should I remove it or leave it just in case we decide to implement it?

2024-12-13 12:35 UTC, mdesautel commented on types/types.ts
> +  ReceiverID: string;
Yes probably, if the news is destined to be read by multiple users it could be a good thing, I don't know if time will permit though. The attribute 'receiverID' (which I assume you're talking about from the placement of your comment) is not really for that, it is more to filter on which users the news should be accessible to.

2024-12-16 14:08 UTC, userdarius approved these changes

2024-12-16 14:08 UTC, userdarius commented on types/types.ts
> +  ReadAt: Timestamp;
I think we should remove it

2024-12-16 14:08 UTC, userdarius commented on types/types.ts
> +  ReceiverID: string;
Yes we can leave it as is and if we have time we can add it but should not be a priority

2024-12-16 22:28 UTC, merged