Feat/settings profile
Swent-Fall-2024-team-10/leazy pull request #250
Opened 2024-12-13 08:16 UTC by baudoin-csp

2024-12-15 11:21 UTC, AdrienDeschenaux requested changes
Hey Baudoin! Thank you for your work, I greatly appreaciate that you took some time to organize the pictures in you PR!

## General overview 

I think that this PR contains a good amount of functionalities that are important for the app to feel complete. However there is a few points that needs to be modified before we can merge this into main, most of those are regarding styling. I will quickly summarize what I think should be modified before it can be merged on main 

## Summary of the changes requested : 

### Styling : 

Overall I greatly appreciate that you reused existing styling! But I think there is some places where you should have more shared styling : Buttons and text input fields, you should also change the labeling of the `change password` section being slightly changed

EDIT : please note that most of the requests I did for the buttons and input text fields should be applied to all of them !

### Bug : 

I catched only one bug which was that you cannot change the email. It seems that we cannot update the email for now. The error thrown is a firebase error telling us that we need to verify the new email before changing the email

2024-12-15 12:27 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +                    style={[appStyles.inputFieldLabel, { marginLeft: '0%' }]}
Because the original component has a `marginLeft` with` 5%` I think, which I didn't want for the design of my screen.

2024-12-15 12:51 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +      <ScrollView
That's a good idea! I'll implement it in the next commit 👍

2024-12-15 12:52 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +      };
Good catch! I remove it and replace it with user.type

2024-12-15 12:59 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +          />
I modified it as you said! Great remark :)

2024-12-15 12:59 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +          />
Sure!

2024-12-15 13:02 UTC, baudoin-csp commented on firebase/auth/auth.ts
> +export async function resetUserPassword(currentPassword: string, newPassword: string) {
Done :)

2024-12-15 13:02 UTC, baudoin-csp commented on app/screens/auth/SignUpScreen.tsx
> +    if (password !== confirmPassword) newErrors.confirmPassword = MGS_PWD_MATCH;
Thanks!

2024-12-15 13:11 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +              label='Reset Password'
Yes you're right! I modified it

2024-12-15 13:11 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +            <Spacer height={20} />
I find it more consistent to use a spacer as I use them in my scren

2024-12-15 13:16 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +    }
Done 👍

2024-12-15 13:17 UTC, baudoin-csp commented on app/screens/auth/SettingsScreen.tsx
> +            />
I don't understand exactly the issue here. Maybe we can discuss it via Telegram or in person if you want

2024-12-15 14:05 UTC, AdrienDeschenaux commented on app/screens/auth/SettingsScreen.tsx
> +            />
The problem is that the input text fields styling is different from what we should have, after having a look at your screen shots I suspect that IOS emulator and android emulator have different default values for the height, therefore you should have styling for that, otherwise the rendering will not be the same across the platforms, also you should set the background color of the text input, (since we had a background color for every other text input, it feels weird to have a white background for those)

2024-12-15 14:07 UTC, AdrienDeschenaux commented on app/screens/auth/SettingsScreen.tsx
> +                      placeholder={`Enter your ${field}`}
Yes I was mentioning this component, if you look at how it is being used in ReportScreen (and how it looks on the screen) you'll see that the styling is not the same as with your screen (moreover I added a comment below about the default height of the input text field with respect to the device used, I re-opened the discussion)

2024-12-15 14:10 UTC, AdrienDeschenaux commented on app/screens/auth/SettingsScreen.tsx
> +            <Spacer height={20} />
I think that at the beginning of the project I created the spacer because I wasn't experienced enough with react native and I thought it was a good idea, but now I think it's better to use margin to be honest but it's fine for me if you want to leave it like that

2024-12-16 08:43 UTC, AdrienDeschenaux approved these changes

2024-12-16 10:38 UTC, merged