Feat/code-generation-&-tenant-profile
Swent-Fall-2024-team-10/leazy pull request #88
Opened 2024-11-01 13:53 UTC by baudoin-csp

## Tenant Registration, Header Enhancement, and Backend Integration
### Summary
This PR implements the following features:

### 1. Tenant Registration Form

<img src="https://github.com/user-attachments/assets/dc74c21c-be3f-4491-917a-de5af9e7fc0b" alt="Simulator Screenshot - iPhone 15 - 2024-11-01 at 14 36 49" width="300"/>

- Developed a registration form to capture tenant details, including:
- Integrated validation for tenant code and data submission to Firestore.

### 2. Header Modification
- Modify the header with conditional rendering based on a `showMenu` boolean prop:

  - When `showMenu` is `true`, the header displays a menu and user icon.
  <img width="310" alt="Screenshot 2024-11-01 at 14 50 27" src="https://github.com/user-attachments/assets/604f6563-1535-4ff0-8903-0ff31feed22a">

  - When `showMenu` is `false`, it displays a back button and a sign-out icon.
  <img width="310" alt="Screenshot 2024-11-01 at 14 49 26" src="https://github.com/user-attachments/assets/5c521d44-f3ce-46ea-963d-b2bbc127bce2">
- Implemented sign-out functionality with navigation to the SignIn screen on success and error handling via a toast message.

## Needs to be explained by @userdarius 
- Screens for code generation from landlord's side and code approval from the tenant's side: do not modify this

2024-11-08 22:07 UTC, AdrienDeschenaux requested changes
Hey Darius and Baudoin! Thank you for the work done, 

### Overall impression

This PR is quite complete and contains the functionalities and screen we wanted to integrate for those issues, unfortunately there is some working functionalities that are currently working on main (Report an issue) that are not working on this branch, I think you might have forgotten to modify code everywhere or you accidentally deleted a line. Either way this should not be much a problem as a fix should be pretty easy to implement

I really like the 'share code' option I think this is a great addition to what we had in mind 

### Styling 

I know I might sound like a broken record on this, but I want to emphasize the importance of consistent styling. It would be ideal if we could reuse existing styling elements as much as possible, especially for the new code entry and code generation screens integrated through this PR. Ensuring these use shared styling (like the `TenantFormScreen.tsx`) will save us from potential refactoring down the line. I realize this may seem like a picky request, but being mindful of styling now will prevent time-consuming adjustments later. 

(Note: you don't need to refactor the screens that are already on main as I'm currently working specifically on those for the refactoring of the style sheets)

Thank you for understanding!

2024-11-09 08:46 UTC, baudoin-csp commented on app/index.tsx
> +      <Drawer.Screen name="Report" component={ReportScreen} />
Are you talking about the Report Screen?

2024-11-09 08:52 UTC, baudoin-csp commented on types/types.ts
> +};
You can find the answer in the #82 : _createUser function and user type: remove the uid field because we don't want to take care of the generation of a UID. Firestore automatically creates one._
When creating a User object Firestore automatically creates a UID attached to the object. Hence there is no need to create a field. 
If we keep the `uid` field, the function would require a UID to be provided before creating the user in Firestore.

2024-11-09 08:53 UTC, baudoin-csp commented on app/screens/tenant/TenantFormScreen.tsx
Thanks Adrien!

2024-11-09 10:49 UTC, baudoin-csp commented on types/types.ts
> +};
I just pushed a corrected version implementing the userID. We need it because it is the between the authentication and the User object.

2024-11-09 10:52 UTC, AdrienDeschenaux commented on app/index.tsx
> +      <Drawer.Screen name="Report" component={ReportScreen} />
Yes I think there might have been a mistake while doing some merging which ended up with the index.tsx of your branch to still have the ReportScreen being accessible from the drawer (which shouldn't be the case), this can be fixed by removing the ReportScreen from here (it should be already listed in an other navigation stack I had created some times ago (I think this stack already exist in the code of your branch that's why I suspect a small typo in a merge) it should be fine once you removed this line from the code (line 93)

2024-11-09 10:53 UTC, baudoin-csp commented on app/index.tsx
> +      <Drawer.Screen name="Report" component={ReportScreen} />
I removed it, you can check it in the last commit

2024-11-09 12:45 UTC, userdarius commented on app/screens/tenant/TenantFormScreen.tsx
Hi I have a small concern with this screen. When the user signs up for the first time before entering a code they are asked to provide a name last name and email as well as a password, then when they enter a valid code they are forwarded to the ```TenantFormScreen``` screen which asks them for the same information again which I find counter intuitive and puzzling as a user. I think we should either import those values from the signup screen and display them in a way that it is clear that they don't have to reenter that information. See below for the relevant screenshots:
First ```SignUpScreen``` :
<img width="337" alt="Screenshot 2024-11-09 at 13 41 30" src="https://github.com/user-attachments/assets/ea85fbb9-1489-438d-8a94-a7d3953bf7bd">

Then the ```TenantFormScreen``` :
<img width="348" alt="Screenshot 2024-11-09 at 13 43 15" src="https://github.com/user-attachments/assets/8f72f09a-ed5c-4e25-8a25-1fc52bfd272a">

2024-11-09 13:16 UTC, userdarius commented on app/index.tsx
> +      />
Hi @AdrienDeschenaux great remark I've also been thinking about this and I agree that we should separate the navigation stacks entirely based on the user type. I think for now this is fine since we still do not differentiate properly in the rest of the app but as this is a task for this week I think this modification should be part of it. Additionally this issue is also present regarding the CreateCodeScreen which should only be displayed on the HomeDrawerNavigator for the Landlord and not the tenants e.g. TenantHomeDrawerNavigator and LandlordHomeDrawerNavigator since right now we only have one HomeDrawerNavigator for both. Like you said I think it will be more modular and easy to work with if we implement a separate TenantAuthenticationStack and LandlordAuthenticationStack as well but regarding this PR in particular I don't think it matters too much.

2024-11-09 13:16 UTC, userdarius commented on app/screens/auth/CodeApprovedScreen.tsx
> +});
Yes I agree I'll push something today for this before we merge anything

2024-11-09 13:23 UTC, userdarius commented on types/types.ts
> +};
Please see comment above

2024-11-09 15:24 UTC, baudoin-csp commented on app/screens/tenant/TenantFormScreen.tsx
I fix this problem in this commit: https://github.com/Swent-Fall-2024-team-10/leazy/pull/88/commits/364e92b176537d1511252ed3370fc9716ee1600a

I removed the name and last name field as we ask for it afterwards.
<img width="369" alt="Screenshot 2024-11-09 at 16 23 45" src="https://github.com/user-attachments/assets/45a7d5c7-e4d2-49b3-bf71-a87f89f0b3b7">

2024-11-09 15:26 UTC, baudoin-csp commented on types/types.ts
> +};
I used this code to have a modular code. Why can't we keep it?

2024-11-09 15:27 UTC, baudoin-csp commented on types/types.ts
> +};
Is it resolved? @userdarius

2024-11-09 16:14 UTC, AdrienDeschenaux commented on app/index.tsx
> +      />
After thinking about this again today, I agree with what you just said, since we planned a task about splitting the tenant and landlord screen (and therefore creating different stacks) it is indeed not necessary to do it there, 

I'll set as resolved this conversation,

2024-11-09 16:16 UTC, AdrienDeschenaux commented on types/types.ts
> +};
In think it was a conflict of merging, in main those are not in types.ts file anymore but rather in the styles.ts, the Color should reference the Color in styles.ts not in types.ts

2024-11-09 16:53 UTC, userdarius commented on app/screens/auth/CodeApprovedScreen.tsx
> +});
See https://github.com/Swent-Fall-2024-team-10/leazy/pull/88/commits/1fabebca362ce59399bde308d0961f5c585199fb

2024-11-09 16:53 UTC, userdarius commented on app/screens/landlord/CreateNewCode.tsx
See https://github.com/Swent-Fall-2024-team-10/leazy/pull/88/commits/1fabebca362ce59399bde308d0961f5c585199fb

2024-11-09 16:59 UTC, userdarius commented
Here are the new screens for the code creation, code entry and code approval frontends using shared styling and reusable components:

<img width="401" alt="Screenshot 2024-11-09 at 17 57 36" src="https://github.com/user-attachments/assets/49ffd9a1-324c-404b-87eb-8aa4b705ce0c">
<img width="405" alt="Screenshot 2024-11-09 at 17 58 08" src="https://github.com/user-attachments/assets/b82746d3-7bd0-41d1-a146-d3db39c9b3be">
<img width="399" alt="Screenshot 2024-11-09 at 17 58 34" src="https://github.com/user-attachments/assets/542ad31e-834c-4e02-8be0-b108960f5e11">

2024-11-09 19:12 UTC, baudoin-csp commented on types/types.ts
> +};
Fixed: [65b558d](https://github.com/Swent-Fall-2024-team-10/leazy/pull/88/commits/65b558d2db29484f4f688b623b144095a5b8a032)

2024-11-10 08:56 UTC, AdrienDeschenaux approved these changes
Hello again Darius and Baudoin, Thanks a lot for the changes you made! 
Now it's working it is ready for merging into main

2024-11-10 08:57 UTC, merged